### ISSUE TITLE
Folder structure in .zip

### ISSUE THREAD

**Issue by Deleetdk** [onbjerg/emel#2]
The current implementation results in root folders being included in the path in the .zip file. For instance: 

Y:\Backup hjemmeside\Journal\2015-11-09_05_43\Backup hjemmeside\Journal\2015-11-09_05_43

This should be instead:

Y:\Backup hjemmeside\Journal\2015-11-09_05_43

The root folders are empty tho, so isn't including the files in the folders.

**Comment by onbjerg** [comment]
https://github.com/onbjerg/emel/commit/404cc14d6f71c5770a06e3b79826e2a658491b37 should fix this. Note that https://github.com/onbjerg/emel/commit/e24530eeadc10da90a37ad03234307a25e57418b implements actually compressing files in the zip, but this requires the [zlib](https://docs.python.org/2/library/zlib.html#module-zlib) module as described [here](https://docs.python.org/2/library/zipfile.html#zipfile.ZIP_DEFLATED)
